### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nFeyz** [Koekkruimels/tera-healer-toolbox#1]
is the basic command ht?
why im getting error when i use the command?
 ERROR: TypeError: warningsTimeout.values(...).forEach is not a function
    at clearData (........TeraProxyCaali\mods\Healer Toolbox\index.js:423:34)
    at String.<anonymous> (............TeraProxyCaali\mods\Healer Toolbox\index.js:41:9)

**Comment by Koekkruimels** [comment]
I will look into the issue today.

The **warningsTimeout** is of type Map and values() should exist, I also use this type a lot more in mod, so you should see this problem occur more often. We will see!

_This "error" should not affect the functionality of the command and the mod!_
