### ISSUE TITLE
Outdated and cannot be used anymore.

### ISSUE THREAD

**Issue by Burakkii** [Koekkruimels/tera-healer-toolbox#3]
![Снимок экрана 2021-08-09 100842](https://user-images.githubusercontent.com/88650560/128672373-a4a5d44d-6b88-4ee7-b37c-e463c4713af8.png)
This module soo good! Could u do something about it, if u please?

**Comment by Koekkruimels** [comment]
Could you test it again?

I do no longer play or have Tera installed, these changes are based on data I can see on the Github page of Tera Toolbox, so no promised can be made if these small changes will work.

CC #1
