### ISSUE TITLE
Healer toolbox

### ISSUE THREAD

**Issue by xdname** [Koekkruimels/tera-healer-toolbox#4]
![Heal toolbox 1](https://user-images.githubusercontent.com/50274231/134002869-45b2cd71-e81f-4ead-b829-c8bcfb079e8c.jpg)
Can anyone help with this please?

**Comment by Koekkruimels** [comment]
Could you test it again?

I do no longer play or have Tera installed, these changes are based on data I can see on the Github page of Tera Toolbox, so no promised can be made if these small changes will work.

CC #3
